### ISSUE TITLE
MLabs

### ISSUE THREAD

**Issue by AltiMario** [w3f-webops/graypaper-website#20]
I would like to list/change the following JAM client implementation:

- Name: "JAMLabs"
- Description: "Haskell implementation of the JAM protocol. Currently not publicly visible."
- Optional Website: ""
- Language: "Haskell"
- Language Set: "C"
- Finished milestones: 0
- Optional contact (email/matrix/telegram etc): ""

**Comment by AltiMario** [comment]
hi @peetzweg, the team doesn't have a telegram group yet but I'm in the Jam Chat matrix channel and MLabs ltd can be reached via email.
Here are the contacts: 
info@mlabs.city  
@altimario:matrix.org

Thank you very much

**Comment by peetzweg** [comment]
@AltiMario thank you! Seems like you are only in the Jam chat channel, can highly recommend the Gray Paper channel as well for implementers. 

https://matrix.to/#/#graypaper:polkadot.io

**Comment by AltiMario** [comment]
@peetzweg ,I just joined the channel, thanks ;-)
