### ISSUE TITLE
Client Listing: rjam

### ISSUE THREAD

**Issue by 0xa11ce** [w3f-webops/graypaper-website#21]
I would like to list/change the following JAM client implementation:

- Name: "rjam"
- Description: "JAM Rust client implementation"
- Optional Website: ""
- Language: "Rust"
- Language Set: "B"
- Finished milestones: 0
- Optional contact (email/matrix/telegram etc): ""

**Comment by peetzweg** [comment]
Closed by https://github.com/w3f-webops/graypaper-website/commit/84b508435489816f3c3f8afa90f32591176f3c95
