### ISSUE TITLE
Client Listing: Universaldot

### ISSUE THREAD

**Issue by stojanov-igor** [w3f-webops/graypaper-website#40]
I would like to list/change the following JAM client implementation:

  description: "JAM client implementation in Rust",
    homepage: "https://universaldot.foundation",
    name: "UNIVERSALDOT",
    lang: "Rust",
    lang_set: "B",
    milestone: 1,
    contact: [info@universaldot.foundation],

Update available via the following pull request: https://github.com/w3f-webops/graypaper-website/pull/39

**Comment by peetzweg** [comment]
Closed by #39
