### ISSUE TITLE
Client Listing: Clawbird

### ISSUE THREAD

**Issue by ltfschoen** [w3f-webops/graypaper-website#49]
I would like to list/change the following JAM client implementation:

- Name: "Clawbird"
- Description: "JAM client implementation in Rust"
- Optional Website: "https://github.com/ltfschoen/jam"
- Language: "Rust"
- Language Set: "B"
- Finished milestones: 0
- Optional contact (email/matrix/telegram etc): "@ltfschoen:matrix.org"

Update available via the following pull request [#50](https://github.com/w3f-webops/graypaper-website/pull/50)

**Comment by peetzweg** [comment]
Closed by #50
