### ISSUE TITLE
Change JAM-DUNA web site/contact

### ISSUE THREAD

**Issue by sourabhniyogi** [w3f-webops/graypaper-website#53]
- Name: "JAM DUNA"
- Description: "Colorful Notion JAM"
- Optional Website: "https://github.com/jam-duna/jamtestnet"
- Language: "Go"
- Language Set: "A"
- Finished milestones: 0
- Optional contact (email/matrix/telegram etc): "@sourabhniyogi"

**Comment by peetzweg** [comment]
Closed by #54.
